# Generated by Django 3.0.2 on 2020-01-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200126_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
